# use ubuntu image as base and copy go code
FROM ubuntu
RUN apt update
RUN apt install -y git golang
RUN mkdir /app
COPY ./pkg/ /app/pkg
COPY . /app
WORKDIR /app
RUN go build -o /app/main /app/main.go
CMD ["/bin/bash"]