name: Update Winget Manifest

on:
  release:
    types: [published]

jobs:
  update-winget-manifest:
    runs-on: windows-latest
    steps:
      - uses: vedantmgoyal2009/winget-releaser@main 
        with:
          identifier: therealpaulgg.ssh-sync
          version: ${{ github.ref_name }}
          release-tag: ${{ github.ref_name }}
          token: ${{ secrets.ACCESS_TOKEN_CLASSIC }}
